canyugs/hitcon-online

common/maplib/map-state.mjs, sites/game-client/game-client.js
Note: Please "rebase and merge" when you want to merge this PR.
=> Add game client and map state

sites/game-client/input-manager.mjs, sites/game-client/map-render.mjs
因為原本設計沒有取消註冊的設計，所以增加回傳一個 off function 來關閉
然後目前 MapRender 沒有公開的取得 canvas 的方法，這邊先加入一個 `getCanvas`
=> feat: implement input manager

run/config/default.json, services/main/static-asset-server.mjs, sites/game-client/client.html, sites/game-client/map-render.mjs
(Ignore the debug config thing, I just piggy back it here because it's small)
=> Load actual map in client side

common/extlib/client-extension-helper.mjs, common/extlib/client-extension-manager.mjs, common/extlib/package.json
完成初步的Client Extension Manager 和 Client Extension Helper。僅完成初步的架構，並沒有測試。
=> Finish skeleton code of client extension

common/maplib/map.mjs
Will fix the performance issue later.
=> Add cellset functionality to GameMap

common/extlib/client-extension-manager.mjs, extensions/helloworld/client.mjs
完成 onExtensionBroadcast 以及其他額外增加的 type checking。
=> Finish onExtensionBroadcast

common/extlib/extension-helper-base.mjs, common/maplib/map.mjs, extensions/cellsettest/client.mjs, extensions/cellsettest/in-div.ejs, extensions/cellsettest/in-gateway.mjs, extensions/cellsettest/package.json, extensions/cellsettest/standalone.mjs, services/gateway/all-area-broadcaster.mjs, services/gateway/gateway-service.mjs, sites/game-client/game-client.mjs
1. The extension should be able to request cell set updates (set/unset) in standalone and in-gateway.
2. Added an example extension to demonstrate how to request a cell set update.
=> Add dynamic cellset broadcast

.pnp.js, common/extlib/extension-helper-base.mjs, extensions/cellsettest/client.mjs, extensions/cellsettest/standalone.mjs, services/gateway/all-area-broadcaster.mjs, yarn.lock
1. Just found that I didn't enable ESLint, and there are some indentation errors. Thanks to @ktpss95112 for reminding me.
2. Add monorepos to .pnp.js and yarn.lock
3. No new features or functional changes in this PR.
=> Fix some minor errors

sites/game-client/game-client.mjs, sites/game-client/input-manager.mjs
Refactor input-manager.mjs since the old one is not flexible and lacks a lot of functionality.
=> refactor input manager

common/maplib/map.mjs, extensions/bombman/client.mjs, extensions/bombman/standalone.mjs, run/map/assets.json, run/map/map.json, sites/game-client/game-client.mjs, sites/game-client/input-manager.mjs, sites/game-client/map-renderer.mjs, sites/game-client/ui/main-ui.mjs
Refactor `MapRenderer` to support a more flexible rendering mechanism.
=> Enable extension to draw its customized layer

common/extlib/extension-helper-base.mjs, extensions/chat/client.mjs, extensions/chat/standalone.mjs, services/gateway/gateway-service.mjs
1. Modify extension helper to call teleport function of RPC
2. Add chat command
=> Teleport feature done

common/maplib/map.mjs, common/rpc-directory/directory.mjs, run/map/map.json, services/gateway/gateway-service.mjs
Rebase to PR #94 and Change Spawn Point Arrays' type.
=> Spawn Point

common/extlib/client-extension-manager.mjs, common/extlib/extension-helper-base.mjs, common/extlib/extension-helper-standalone.mjs, common/extlib/extension-manager.mjs, common/maplib/graphic-asset.mjs, common/maplib/map.mjs, common/rpc-directory/data-store.mjs, common/rpc-directory/directory.mjs, common/rpc-directory/handler.mjs, extensions/blank/common/client.mjs, extensions/items/common/client.mjs, extensions/items/standalone.mjs, sites/game-client/game-client.mjs
To minimize the merge conflicts and not block further development, I will merge this PR on 12th Aug (Thu.).
=> Refactor console.log, console.error, etc.

common/rpc-directory/multi-process-RPC-directory.mjs, run/config/default.json, run/start-all.mjs, services/assets/asset-server.mjs, services/gateway/all-area-broadcaster.mjs, services/main/asset-server.mjs, services/main/gateway-server.mjs, services/main/main-server.mjs, services/standalone/standalone-extension.mjs
1. PR #99 accidentally remove the changes to asset server from PR #84 , this PR adds the changes back.
2. In multiprocess mode, GameState in the gateway services should be updated when received updates from Redis.
=> Fix the problem that PR #99 accidentally removed code from PR #84, and GameState not synchronizing correctly

common/maplib/game-state.mjs, sites/game-client/map-renderer.mjs, sites/game-client/ui/map-renderer-overlay.mjs
In order not to block the development of @zeze-zeze , I'm not requesting any review.
If this PR has any errors, please feel free to contact me.
=> Refactor map-renderer and game-state

docker/docker-compose.yml, docker/generate-nginx-conf.py, docker/generate-nginx-conf.sh, docker/nginx-template.conf, docs/docker.md, run/start-all.mjs
1. Move Nginx configuration generation to the `nginx` container.
2. Fix a bug in configuration script.
3. Add `start-all.mjs` back since it was accidentally modified by the ESLint commit.
=> Update Nginx setup and configuration

common/extlib/client-extension-manager.mjs, sites/game-client/map-renderer.mjs
* for chat extension
It seem like `in` operator only check index number in Arrays
[see docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in#examples)
=> Fix display name and chat extension

.pnp.js, yarn.lock
=> Add yarn install result for map watermark

.pnp.js, common/extlib/client-extension-manager.mjs, common/extlib/extension-helper-base.mjs, common/gamelib/game-state.mjs, common/gamelib/package.json, common/gamelib/player.mjs, common/rpc-directory/directory.mjs, extensions/cellsettest/in-gateway.mjs, extensions/cellsettest/standalone.mjs, extensions/jitsi/common/client.mjs, services/gateway/all-area-broadcaster.mjs, services/gateway/gateway-server.mjs, services/gateway/gateway-service.mjs, services/main/main-server.mjs, services/standalone/standalone-extension.mjs, sites/game-client/client.ejs, sites/game-client/game-client.mjs, sites/game-client/map-renderer.mjs, yarn.lock
=> Refactor player: create a `Player` class

common/extlib/client-extension-manager.mjs, extensions/chat/common/client.mjs, extensions/jitsi/common/client.mjs, services/assets/asset-server.mjs
=> Add '/common' back to the URL path of the extensions' static resources

.pnp.js, extensions/playerlist/common/client.mjs, extensions/playerlist/common/playerlist.svg, extensions/playerlist/in-div.ejs, extensions/playerlist/in-gateway.mjs, extensions/playerlist/package.json, extensions/playerlist/standalone.mjs, run/config/default.json, yarn.lock
The way getting player list is to request server once a second, which can be more efficient if we can find a way to update player list.
=> Extension playerlist basic feature done

.pnp.js, common/interactive-object/client.mjs, common/interactive-object/exampleConfig.mjs, common/interactive-object/package.json, common/interactive-object/server.mjs, common/maplib/map.mjs, extensions/dialog/common/client.mjs, extensions/npc/README.md, extensions/npc/common/client.mjs, extensions/npc/in-gateway.mjs, extensions/npc/package.json, extensions/npc/standalone.mjs, run/config/default.json, run/npc/example-npc1.json, services/gateway/gateway-service.mjs, sites/game-client/client.css, sites/game-client/input-manager.mjs, sites/game-client/map-renderer.mjs, yarn.lock
=> Interactive object & NPC extension

.gitignore, .pnp.js, extensions/iframe/common/client.mjs, extensions/iframe/in-div.ejs, extensions/iframe/in-gateway.mjs, extensions/iframe/package.json, extensions/iframe/standalone.mjs, run/config/default.json, run/map/assets.json, run/map/map.json, sites/game-client/ui/overlay.mjs, yarn.lock
open/close iframe by map configuration
=> feat(ext-iframe): support overlay iframe with map configuration

sites/game-client/client.ejs, sites/game-client/game-client.mjs, sites/game-client/ui/error-modal.mjs
=> Error modal: Move the modal into game-client

common/interactive-object/server.mjs, extensions/dialog/standalone.mjs, run/npc/example-npc2.json, services/gateway/gateway-service.mjs
The NPC asks players' key and teleports them to correct place.
=> NPC Teleport

common/gamelib/move-check.mjs, common/gamelib/player.mjs, run/map/assets.json, services/gateway/gateway-service.mjs, sites/game-client/client.ejs, sites/game-client/game-client.mjs, sites/game-client/input-manager.mjs, sites/game-client/map-renderer.mjs
Still working in progress
9/24 updated: done
=> refactor gateway-service, add player smooth movement, refactor input manager

extensions/iframe/in-div.ejs
As title.
I feel honored to have the PR with the shortest edit distance :)
=> Remove the default value for iframe to prevent loading the /client.html twice

extensions/MapWatermark/common/client.mjs, sites/game-client/map-renderer.mjs
The function name "_drawWatermark" had been changed into "_drawWaterMark", so it couldn't be called.
=> Fix watermark

common/extlib/extension-helper-base.mjs, services/gateway/gateway-service.mjs
Add comment in the code that John wrote.
=> Get token comment

extensions/chat/common/client.mjs, sites/game-client/client.ejs, sites/game-client/game-client.mjs
now announcement can triggered by command in the chat extension.
not supported yet:
* permission check
* announcement timeout (?)
=> Command for Announcement

sites/game-client/client.css, sites/game-client/client.ejs, sites/game-client/context-menu.css, sites/game-client/error-modal.css, sites/game-client/warning.svg
* z-index of context-menu has changed to 99
=> add style for ErrorModal

extensions/chat/common/client.mjs, extensions/playerlist/common/client.mjs, extensions/point-system/common/client.mjs, sites/game-client/client.ejs, sites/game-client/context-menu.css, sites/game-client/ui/context-menu.mjs, sites/game-client/ui/main-ui.mjs
1. Adopt the new UI for the context menu.
2. Add / Fix context menu integration for `playerlist`, `chat`, and `point-system`.
=> New UI and extension integration for the player context menu

common/interactive-object/server.mjs, extensions/dialog/common/client.mjs, extensions/npc/standalone.mjs, run/npc/Bulletin.json
1. Check permission in state
2. Edit dialog
=> Bulletin npc

extensions/escape-game/common/client.mjs, extensions/escape-game/standalone.mjs, extensions/npc/standalone.mjs, run/npc/team-manager.json, run/terminal/example-terminal1.json, run/terminal/example-terminal2.json, terminal-server/container-handler.mjs
The team manager for the game （密室逃脫、駭客貓歷險記？）
Still work in progress.
=> The team manager for the game

extensions/escape-game/standalone.mjs
`await this.helper.callS2sAPI('escape-game', 'queryPlayerStatus', '<player ID>'));`
=> Add s2s function to query player team status

extensions/jitsi/common/client.mjs, extensions/jitsi/common/jitsi.mjs, extensions/jitsi/in-div.ejs, extensions/setting/common/client.mjs, sites/game-client/client.css, sites/game-client/ui/main-ui.mjs
1. Fullscreen
2. Sort by sound
3. Draft for input device selection, not yet done.
=> Add fullscreen and voice sorting to Jitsi

run/npc/example-npc1.json
This PR avoid to mislead generating wrong npc json file about items.
=> correct items-related amount type about example npc1

extensions/point-system/common/client.mjs, extensions/point-system/standalone.mjs, run/config/default.json, run/config/production.json
=> Update point system to new schema; send notification when points are transferred

sites/game-client/avatar-selection.css
=> make selection div scrollable for more characters and small screen

common/gamelib/move-check.mjs, common/gamelib/movement-manager.mjs, sites/game-client/input-manager.mjs
1. Client side cell occupation check
2. Fix input manager TODO and bug
=> Fix client side bugs

extensions/jitsi/common/client.mjs, extensions/jitsi/common/jitsi.mjs, extensions/jitsi/standalone.mjs, run/config/default.json, run/config/production.json
=> Fetch connection info of Jitsi from the config file

extensions/escape-game/standalone.mjs, extensions/items/standalone.mjs
=> Remove player's item after quitting the team

extensions/jitsi/common/jitsi.mjs
1. Add a lock to Jitsi connection and disconnection.
2. Use the built-in audio level detector instead of the self implemented one.
=> Several Jitsi fixes

extensions/escape-game/standalone.mjs, extensions/point-system/common/client.mjs
```
"giveCode": {
"func": "giveRedeemCode",
"kwargs": {
"redeemCodes": ["1", "2", "3", "4"],
"eventName": "test",
"nextState": "exit",
"errorState": "exit"
}
},
```
=> Add state function for distributing redeem codes

extensions/iframe/common/client.mjs, extensions/iframe/in-div.ejs, sites/game-client/client.ejs, sites/game-client/fullscreen.svg, sites/game-client/ui/user-overlay.mjs
* with basic user overlay (can toggle show/hide state)
=> apply iframe UI

extensions/jitsi/common/client.mjs, extensions/jitsi/common/jitsi.mjs
=> Exit fullscreen when the focused player left

extensions/npc/common/client.mjs, sites/game-client/client.ejs, sites/game-client/map-renderer.mjs
Currently, I only added `NPCHighlight: true` to NPC extension. Terminal or other interactive objects should also be modified like this:
https://github.com/ktpss95112/hitcon-online/blob/6273d8bb71ef75eef486cefa5638f1a4f6b72895/extensions/npc/common/client.mjs#L74-L76
=> NPC name highlight

.pnp.js, extensions/escape-game/standalone.mjs, extensions/point-system/common/client.mjs, extensions/point-system/package.json, extensions/point-system/standalone.mjs, run/config/default.json, run/config/production.json, yarn.lock
=> Move the point system address to the config

extensions/escape-game/standalone.mjs
This prevent run/terminall/.gitkeep been loaded.
=> Add file extension filter to terminal 

sites/game-client/map-renderer.mjs
=> Create function for full map snapshot

extensions/escape-game/common/client.mjs, extensions/escape-game/standalone.mjs, run/config/default.json, run/map/assets.json, tiled-maps/scripts/generateMapConfig.mjs
1. created a layer on the map for doors
2. added an e2s API to trigger the door
=> a door in the map triggered by the e2s api

.eslintrc.yml, common/gamelib/move-check.mjs, common/gamelib/movement-manager.mjs, services/gateway/gateway-service.mjs
=> Fix bug of ghost mode

extensions/bombman/standalone.mjs, extensions/npc/standalone.mjs, run/npc/bombman-npc.json
=> add bombman npc
